/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppMenu: typeof import('./components/AppMenu.vue')['default']
    AudioVisualizer: typeof import('./components/AudioVisualizer.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VideoParticipant: typeof import('./components/VideoParticipant.vue')['default']
    WebsiteFooter: typeof import('./components/WebsiteFooter.vue')['default']
    WebsiteMenu: typeof import('./components/WebsiteMenu.vue')['default']
  }
}
